;;; bufferwizard.el --- Buffer wizard  -*- lexical-binding: t; -*-

;; Copyright (C) 2024-2026 James Cherti | https://www.jamescherti.com/contact/

;; Author: James Cherti <https://www.jamescherti.com/contact/>
;; Version: 1.1.0
;; URL: https://github.com/jamescherti/bufferwizard.el
;; Keywords: convenience
;; Package-Requires: ((emacs "26.1"))
;; SPDX-License-Identifier: GPL-3.0-or-later

;; This file is free software; you can redistribute it and/or modify
;; it under the terms of the GNU General Public License as published by
;; the Free Software Foundation; either version 2, or (at your option)
;; any later version.

;; This file is distributed in the hope that it will be useful,
;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;; GNU General Public License for more details.

;; You should have received a copy of the GNU General Public License
;; along with GNU Emacs.  If not, see <https://www.gnu.org/licenses/>.

;;; Commentary:
;; The **bufferwizard** Emacs package provides a collection of helper functions
;; and commands for managing buffers.

;;; Code:

;;; Group

(defgroup bufferwizard nil
  "Buffer wizard settings and configuration."
  :group 'bufferwizard
  :prefix "bufferwizard-"
  :link '(url-link
          :tag "Github"
          "https://github.com/jamescherti/bufferwizard.el"))

;;; Helper functions

(defun bufferwizard--message (&rest args)
  "Display a message with [bufferwizard] prepended.
The message is formatted with the provided arguments ARGS."
  (apply #'message (concat "[bufferwizard] " (car args)) (cdr args)))

(defun bufferwizard--get-list-buffers (filename)
  "Return a list of buffers visiting the specified FILENAME.

FILENAME is the absolute path of the file to check for associated buffers.

Iterates through all buffers and performs the following check: If a buffer is
visiting the specified FILENAME (based on the true file path), it is added to
the resulting list.

Returns a list of buffers that are associated with FILENAME."
  (let ((true-filename (file-truename filename))
        (list-buffers nil))
    (dolist (buf (buffer-list))
      (when (buffer-live-p buf)
        (let* ((base-buf (or (buffer-base-buffer buf) buf))
               (buf-filename (when base-buf (buffer-file-name base-buf))))
          (when (and buf-filename
                     (string-equal true-filename (file-truename buf-filename)))
            (push buf list-buffers)))))
    list-buffers))

;;; Indirect buffers

;;;###autoload
(defun bufferwizard-clone-indirect-buffer (&optional newname
                                                     display-flag
                                                     norecord)
  "Create an indirect buffer while preserving window state.

This function is an enhanced version of the built-in `clone-indirect-buffer'.

This function creates an indirect buffer with the same content as the current
buffer, ensuring that the point position, window start, and horizontal scroll
position remain unchanged. The original buffer remains intact.

- If NEWNAME is provided, it is used as the name of the new buffer. Otherwise, a
  default name is generated by appending <N> to the current buffer name, where
  N is an incrementing number.
- If DISPLAY-FLAG is non-nil, the new buffer is displayed using `pop-to-buffer'.
  This always happens when called interactively.
- If NORECORD is non-nil, the new buffer is not placed at the front of the
  recently selected buffer list.

This function does not allow cloning buffers whose major mode has a non-nil
`no-clone-indirect' property. If attempted, an error is signaled.

Returns the newly created indirect buffer."
  (interactive
   (progn
     (if (get major-mode 'no-clone-indirect)
         (error "Cannot indirectly clone a buffer in %s mode" major-mode))
     (list (if current-prefix-arg
               (read-buffer "Name of indirect buffer: " (buffer-name)))
           t)))
  ;; Clear Evil mode highlights inherited from the clone operation.
  ;; When creating a cloned indirect buffer, it inherits the active state of the
  ;; base buffer, including the Evil search highlight overlays. This change adds
  ;; a check to evaluate `evil-ex-nohighlight' within the scope of the newly
  ;; created buffer to flush the inherited search state, provided
  ;; `evil-local-mode' is active. This ensures the clone starts with a clean
  ;; visual state.
  (when (and (bound-and-true-p evil-local-mode)
             (fboundp 'evil-ex-nohighlight))
    (evil-ex-nohighlight))

  (let* ((point-pos (point))
         (previous-window (selected-window))
         (buffer (current-buffer))
         (buffer-in-current-window (eq buffer (window-buffer previous-window)))
         (window-start (when buffer-in-current-window
                         (window-start previous-window)))
         (window-hscroll (when buffer-in-current-window
                           (window-hscroll previous-window)))
         (indirect-buffer (clone-indirect-buffer newname display-flag norecord)))
    (when (buffer-live-p indirect-buffer)
      (set-window-buffer nil indirect-buffer)
      (with-current-buffer indirect-buffer
        (goto-char point-pos)
        (let ((current-window (selected-window)))
          ;; Check if the current window is actually displaying the new buffer
          (when (and (window-live-p current-window)
                     (eq (window-buffer current-window) indirect-buffer))
            (when window-start
              (set-window-start current-window window-start t))
            (when window-hscroll
              (set-window-hscroll current-window window-hscroll))))))
    indirect-buffer))

;;;###autoload
(defun bufferwizard-clone-and-switch-to-indirect-buffer (&optional newname
                                                                   norecord)
  "Create an indirect buffer and switch to it.

This function is a variant of `bufferwizard-clone-indirect-buffer', except it
also switches to the new indirect buffer.

This function creates a new indirect buffer with the same content as the current
buffer, preserving point position, window start, and horizontal scroll position.
The original buffer remains unchanged.

The optional argument NEWNAME specifies the indirect buffer name. If NEWNAME is
nil, the name defaults to the current buffer's name with a <N> suffix added,
or by incrementing N in an existing suffix. An error occurs when attempting to
clone a buffer whose major mode symbol has a non-nil `no-clone-indirect'
property.

The optional argument NORECORD, when non-nil, prevents putting this buffer at
the front of the list of recently selected ones.

Returns the newly created indirect buffer."
  (interactive
   (progn
     (if (get major-mode 'no-clone-indirect)
         (error "Cannot indirectly clone a buffer in %s mode" major-mode))
     (list (if current-prefix-arg
               (read-buffer "Name of indirect buffer: " (buffer-name)))
           t)))
  (bufferwizard-clone-indirect-buffer newname nil norecord))

;;;###autoload
(defun bufferwizard-switch-to-base-buffer (&optional buffer)
  "Switch to the base buffer if BUFFER is indirect.
Preserve point, `window-start', and horizontal scrolling."
  (interactive)
  (let* ((target-buf (or buffer (current-buffer)))
         (base-buffer (buffer-base-buffer target-buf)))
    (unless base-buffer
      (user-error "Buffer '%s' is not an indirect buffer"
                  (buffer-name target-buf)))
    (let* ((point-pos (with-current-buffer target-buf (point)))
           (current-buf (current-buffer))
           (window (selected-window))
           (buffer-in-current-window (eq current-buf (window-buffer window)))
           (window-start (when buffer-in-current-window
                           (window-start window)))
           (window-hscroll (when buffer-in-current-window
                             (window-hscroll window))))
      (set-window-buffer nil base-buffer)
      (goto-char point-pos)
      ;; Use the active window after the switch, not necessarily the old one
      (let ((new-window (selected-window)))
        (when (and (window-live-p new-window)
                   (eq (window-buffer new-window) base-buffer))
          (when window-start
            (set-window-start new-window window-start t))
          (when window-hscroll
            (set-window-hscroll new-window window-hscroll)))))))

;;; Search and replace (string)

;;;###autoload
(defun bufferwizard-replace-regexp (from-regexp &optional to-string)
  "Replace occurrences of FROM-REGEXP with TO-STRING.
When TO-STRING is not specified, the user is prompted for input.
This function confirms each replacement."
  (when buffer-read-only
    (error "The buffer '%s' is read-only" (buffer-name)))
  (unless to-string
    (setq to-string (read-string (format "Replace '%s' with: " from-regexp))))
  (let* ((buf (current-buffer))
         (window (selected-window))
         (buffer-in-current-window (eq buf (window-buffer window)))
         (orig-window-start (when buffer-in-current-window
                              (window-start window)))
         (scroll-conservatively 10)
         (search-invisible t))
    (save-excursion
      (let ((undo-handle (prepare-change-group))
            ;; Don't truncate any undo data in the middle of this, otherwise
            ;; Emacs might truncate part of the resulting undo step.
            (undo-outer-limit nil)
            (undo-limit most-positive-fixnum)
            (undo-strong-limit most-positive-fixnum)
            (start (point)))
        (unwind-protect
            (progn
              (activate-change-group undo-handle)
              ;; Replace from the current position
              (query-replace-regexp from-regexp to-string nil start (point-max))
              ;; Replace from the beginning
              (when (> start (point-min))
                (query-replace-regexp
                 from-regexp to-string nil (point-min) (1- start))))
          (accept-change-group undo-handle)
          (undo-amalgamate-change-group undo-handle)
          ;; Sound restoration check: Is the window alive and still holding our
          ;; buffer?
          (when (and orig-window-start
                     (window-live-p window)
                     (eq (window-buffer window) buf))
            (set-window-start window orig-window-start t)))))))

(defun bufferwizard--symbol-at-point-regexp ()
  "Return a regexp that matches the symbol at point."
  (when-let* ((symbol (thing-at-point 'symbol t)))
    (when symbol
      (concat "\\_<" (regexp-quote symbol) "\\_>"))))

;;;###autoload
(defun bufferwizard-replace-symbol-at-point (&optional to-string)
  "Replace occurrences of a symbol at point with a specified TO-STRING.
When TO-STRING is not specified, the user is prompted for input.
This function confirms each replacement."
  (interactive)
  (when buffer-read-only
    (error "The buffer '%s' is read-only" (buffer-name)))
  (let ((region (use-region-p))
        from-string string-start string-regexp)
    (if region
        ;; Region
        (progn
          (setq from-string (buffer-substring-no-properties (region-beginning)
                                                            (region-end)))
          (setq string-start (region-beginning))
          (deactivate-mark)
          (setq string-regexp (regexp-quote from-string)))
      ;; Not a region. Use the symbol at point.
      (setq from-string (thing-at-point 'symbol t))
      (when from-string
        (setq string-start (car (bounds-of-thing-at-point 'symbol)))
        (setq string-regexp (bufferwizard--symbol-at-point-regexp))))

    (when from-string
      ;; Only apply visual highlighting if we need to prompt the user
      (unless to-string
        (let ((highlighted-regexp string-regexp))
          (unwind-protect
              (progn
                (highlight-regexp highlighted-regexp 'lazy-highlight)
                (setq to-string
                      (read-string (format "Replace '%s' with: " from-string)
                                   from-string)))
            (unhighlight-regexp highlighted-regexp))))

      ;; Replace
      (goto-char string-start)
      (let (;; This fixes issues with packages such as aggressive-indent by
            ;; temporarily preventing automatic buffer modifications during the
            ;; replacement. Without this, asynchronous changes (like
            ;; auto-indentation) can shift point and markers, causing replacements
            ;; to affect the wrong text.
            (inhibit-modification-hooks t))
        (bufferwizard-replace-regexp string-regexp to-string)))))

;;; Highlight symbols

(defun bufferwizard-get-symbol-or-region-regexp ()
  "Return the regexp of the selected region or the default symbol at point."
  (if (use-region-p)
      (regexp-quote (buffer-substring-no-properties (region-beginning)
                                                    (region-end)))
    (find-tag-default-as-symbol-regexp)))

(defun bufferwizard-highlight-p ()
  "Return non-nil if the symbol at point is currently highlighted."
  (require 'hi-lock)
  (when (fboundp 'hi-lock--regexps-at-point)
    (when-let* ((regexp (bufferwizard-get-symbol-or-region-regexp)))
      (member regexp (hi-lock--regexps-at-point)))))

;;;###autoload
(defun bufferwizard-highlight-at-point ()
  "Highlight the symbol at point in the current buffer.

This function identifies the symbol at the current point, generates the
appropriate regular expression for it, and applies highlighting using the
built-in `hi-lock' package."
  (interactive)
  (require 'hi-lock)
  (when (and (fboundp 'hi-lock-read-face-name)
             (fboundp 'hi-lock-mode)
             (fboundp 'hi-lock-set-pattern))
    ;; Similar to `hi-lock-face-symbol-at-point'
    (let* ((regexp (bufferwizard-get-symbol-or-region-regexp))
           (hi-lock-auto-select-face t)
           (face (hi-lock-read-face-name)))
      (ignore hi-lock-auto-select-face)
      (when regexp
        (or (facep face) (setq face 'hi-yellow))
        (unless (bound-and-true-p hi-lock-mode)
          (hi-lock-mode 1))
        (hi-lock-set-pattern
         regexp face nil nil
         (if (and case-fold-search search-upper-case)
             (isearch-no-upper-case-p regexp t)
           case-fold-search))))))

;;;###autoload
(defun bufferwizard-unhighlight-at-point ()
  "Remove highlighting for the symbol at point."
  (interactive)
  (require 'hi-lock)
  (when (fboundp 'hi-lock-unface-buffer)
    (when-let* ((regexp (bufferwizard-get-symbol-or-region-regexp)))
      (hi-lock-unface-buffer regexp))))

;;;###autoload
(defun bufferwizard-toggle-highlight-at-point ()
  "Toggle highlighting for the symbol at point.

This function checks if the symbol at point is currently highlighted.
If it is, it removes the highlight; otherwise, it applies the highlight."
  (interactive)
  (if (bufferwizard-highlight-p)
      (bufferwizard-unhighlight-at-point)
    (bufferwizard-highlight-at-point)))

;;;###autoload
(defun bufferwizard-unhighlight ()
  "Remove highlighting of each match to REGEXP.
Interactively, prompt for REGEXP, accepting only regexps previously inserted by
hi-lock interactive functions. If REGEXP is t (or if \\[universal-argument] was
specified interactively), then remove all hi-lock highlighting."
  (interactive)
  (require 'hi-lock)
  (when (fboundp 'hi-lock-unface-buffer)
    (call-interactively #'hi-lock-unface-buffer)))

;;; Highlight code tags

(defcustom bufferwizard-hl-todo-keywords
  '(("TODO"   . font-lock-warning-face)
    ("FIXME"  . font-lock-warning-face)
    ("BUG"    . font-lock-warning-face)
    ("XXX"    . font-lock-warning-face)
    ("DONE"   . font-lock-doc-face)
    ("HACK"   . font-lock-doc-face)
    ("NOTE"   . font-lock-doc-face))
  "Alist of keywords to highlight and their corresponding colors or faces.
Each element is a cons cell: (KEYWORD . COLOR-OR-FACE).
- KEYWORD is a string representing the tag (e.g., \"TODO\").
- COLOR-OR-FACE is either a string specifying a hex color (e.g., \"#FF0000\")
or a symbol representing an existing face (e.g., \\='font-lock-warning-face)."
  :type '(alist :key-type string
                :value-type
                (choice (color :tag "Hex Color (e.g., ##FF0000)")
                        (face :tag "Face Name (e.g., font-lock-doc-face)")))
  :group 'bufferwizard)

(defvar bufferwizard--compiled-hl-todo-keywords nil
  "Internal cache of compiled font-lock keywords for highlighting TODOs.")

(defun bufferwizard--compile-hl-todo-keywords ()
  "Translate `bufferwizard-hl-todo-keywords' into optimized `font-lock' regexps."
  (require 'seq)
  (if (fboundp 'seq-group-by)
      (let* (;; Group the alist by the cdr (the face/color)
             ;; Result:
             ;; '((font-lock-warning-face . (("TODO" . face)
             ;;                              ("FIXME" . face))) ...)
             (grouped-by-face (seq-group-by #'cdr bufferwizard-hl-todo-keywords))
             compiled-rules)

        (dolist (group grouped-by-face)
          (let* ((color-or-face (car group))  ; This group's face/color
                 (entries (cdr group))        ; The list of matching cons cells
                 (keywords (mapcar #'car entries)) ; Extract string keywords

                 ;; regexp-opt safely escapes and builds the fastest possible
                 ;; OR-regexp
                 (regexp (concat "\\_<\\(" (regexp-opt keywords) "\\)\\_>"))

                 ;; Dynamically determine the face property
                 (face-prop (if (stringp color-or-face)
                                (list 'quote (list :foreground color-or-face
                                                   :weight 'bold))
                              (list 'quote color-or-face))))

            ;; Add the optimized rule for this face group to our final list
            (push (list regexp 1 face-prop 'prepend) compiled-rules)))

        compiled-rules)
    (error "Undefined: seq-group-by")))

;;;###autoload
(define-minor-mode bufferwizard-hl-todo-local-mode
  "Minor mode to highlight keywords like TODO, FIXME, etc.

When enabled, this mode dynamically builds font-lock rules from
the key-value pairs defined in `bufferwizard-hl-todo-keywords'."
  :global nil
  :lighter " bw-todo"
  :group 'bufferwizard
  (if bufferwizard-hl-todo-local-mode
      (progn
        ;; Compile and store the keywords so we can reliably remove them later
        (setq bufferwizard--compiled-hl-todo-keywords
              (bufferwizard--compile-hl-todo-keywords))
        (font-lock-add-keywords nil bufferwizard--compiled-hl-todo-keywords t))
    ;; Remove the exact keywords we previously added
    (font-lock-remove-keywords nil bufferwizard--compiled-hl-todo-keywords))

  ;; Refresh font-lock to apply/remove changes immediately
  (when (bound-and-true-p font-lock-mode)
    (if (fboundp 'font-lock-flush)
        (font-lock-flush)
      (with-no-warnings
        (font-lock-fontify-buffer)))))

;;;###autoload
(define-globalized-minor-mode bufferwizard-hl-todo-mode
  bufferwizard-hl-todo-local-mode
  (lambda () (bufferwizard-hl-todo-local-mode 1))
  :group 'bufferwizard)

;;; Clipboard: Paste using indentation

(defun bufferwizard--unindent-string (input-str)
  "Unindent INPUT-STR by removing the minimal common indentation."
  (let* (;; Convert tabs to spaces in a temporary buffer to ensure raw character
         ;; counting accurately reflects visual column depth.
         (clean-str (with-temp-buffer
                      (insert input-str)
                      (untabify (point-min) (point-max))
                      (buffer-string)))

         ;; To split the input string into individual lines for processing.
         ;; It allows iterating over each line to measure its leading whitespace
         ;; independently.
         (lines (split-string clean-str "\n"))

         ;; To track the smallest amount of leading whitespace found across all
         ;; lines. It starts as nil so the first non-empty line encountered can
         ;; establish the initial baseline value.
         (min-indent nil))

    ;; Find the minimum indentation
    (dolist (line lines)
      ;; The line must not be empty
      (unless (string-match-p "^[ \t]*$" line)
        (string-match "^[ \t]*" line)
        ;; And the indent should be lower than the one that has been found
        ;; previously
        (setq min-indent (if min-indent
                             (min min-indent (match-end 0))
                           (match-end 0)))))

    (setq min-indent (or min-indent 0))

    ;; Remove the minimum indentation from all lines
    (mapconcat (lambda (line)
                 (if (>= (length line) min-indent)
                     (substring line min-indent)
                   line))
               lines
               "\n")))

(defun bufferwizard--insert-aligned ()
  "Paste text from the clipboard with the current line's indentation."
  (let ((kill-ring-content (ignore-errors (current-kill 0))))
    (when kill-ring-content
      ;; Clear the active region first so that the destination column depth
      ;; is evaluated from the true post-deletion insertion point.
      (when (use-region-p)
        (delete-region (region-beginning) (region-end)))

      (let* (;; Create the literal whitespace string that will be prepended to
             ;; the pasted lines.
             (new-indentation (make-string (current-column) ?\s))

             ;; Prepare the raw clipboard text by stripping its original
             ;; formatting.
             (text (bufferwizard--unindent-string (string-trim-right
                                                   (substring-no-properties
                                                    kill-ring-content)
                                                   "\n")))

             ;; Construct the final string that will be inserted into the
             ;; buffer.
             (text-to-paste (when text
                              (replace-regexp-in-string
                               "\n"
                               (concat "\n" new-indentation)
                               text))))
        (when text-to-paste
          (insert text-to-paste))))))

;;;###autoload
(defun bufferwizard-paste-indented ()
  "Paste text from the clipboard with the current line's indentation.
It unindents the clipboard content by removing the minimal common leading
whitespace and aligns it perfectly with the cursor's current physical column.
If called outside the minibuffer, the cursor (point) is safely restored to its
original position prior to the paste operation."
  (interactive)
  (if (minibufferp)
      (let ((content (ignore-errors (current-kill 0))))
        (when content
          (insert content)))
    (save-excursion
      (bufferwizard--insert-aligned))))

;;; Clipboard: Copy without indentation

;;;###autoload
(defun bufferwizard-copy-unindented ()
  "Copy the active region or current line with base indentation removed.
If a region is active, copy the text within the region. Otherwise, copy the
current line.
Before adding the text to the kill ring, this function removes the minimal
common leading whitespace from all copied lines. This allows you to extract
blocks of code without preserving their original structural indentation."
  (interactive)
  (let* ((bounds (if (use-region-p)
                     (cons (region-beginning) (region-end))
                   (cons (line-beginning-position) (line-end-position))))
         (start (car bounds))
         (end (cdr bounds))
         (text (buffer-substring-no-properties start end))
         (unindented-text (bufferwizard--unindent-string text)))
    (kill-new unindented-text)))

;;; Point movement

(defcustom bufferwizard-point-ignore-invisible t
  "Non-nil means point movement functions ignore invisible text.
When set to a non-nil value, functions such as
`bufferwizard-point-forward-to-empty-line' and
`bufferwizard-point-backward-to-lower-indentation' will skip over lines that are
currently hidden or invisible. If set to nil, invisible text is included and
evaluated during point movement searches."
  :type 'boolean
  :group 'bufferwizard)

(defun bufferwizard--point-keep-searching-until-empty (_initial-indentation)
  "Return t when the current line is NOT empty."
  (not (looking-at-p "^\\s-*$")))

(defun bufferwizard--point-keep-searching-until-indent-lower (initial-indentation)
  "Return t when the indentation is >= INITIAL-INDENTATION, or the line is empty."
  (or (looking-at-p "^\\s-*$")
      (>= (current-indentation) initial-indentation)))

(defun bufferwizard--point-find-pos (direction func-keep-searching)
  "Get the buffer position of the previous/next line with lower indentation.
DIRECTION is 1 for forward, -1 for backward.
FUNC-KEEP-SEARCHING is a predicate function called with the initial indentation.
Return the buffer position (point) instead of line number for performance.
Return nil if no matching line is found."
  (setq direction (if (>= direction 0)
                      1
                    -1))
  (save-excursion
    (let ((initial-indentation (current-indentation))
          (found nil))
      (while (and (not found)
                  (not (if (> direction 0)
                           (eobp)
                         (bobp)))
                  (zerop (forward-line direction)))
        (unless (or (and bufferwizard-point-ignore-invisible
                         (invisible-p (point)))
                    (funcall func-keep-searching initial-indentation))
          (setq found t)))
      (when found
        (point)))))

(defun bufferwizard--point-move (direction func-keep-searching)
  "Move to the previous/next line matching FUNC-KEEP-SEARCHING criteria.
DIRECTION > 0 moves forward; < 0 moves backward."
  (let* ((region (use-region-p))
         (start (when region (region-beginning)))
         (end (when region (region-end)))
         target-pos)

    (when (and region
               start
               end
               (bound-and-true-p evil-local-mode)
               (fboundp 'evil-visual-state-p)
               (evil-visual-state-p)
               (fboundp 'evil-exit-visual-state))
      ;; For Evil users: Exit visual state explicitly before performing the
      ;; operation. If we do not do this, Evil will automatically restore the
      ;; original point and mark after the command finishes, overriding any
      ;; cursor movement or region updates made within the function.
      (evil-exit-visual-state))

    (setq target-pos (bufferwizard--point-find-pos direction
                                                   func-keep-searching))

    (when target-pos
      (if (not region)
          (goto-char target-pos)
        (when (and start end)
          (if (< target-pos start)
              (progn
                (goto-char target-pos)
                (set-mark end))
            (goto-char target-pos)
            (set-mark start))

          ;; Ensure that the region remains active after the command finishes.
          (setq deactivate-mark nil)
          (activate-mark))))))

;;;###autoload
(defun bufferwizard-point-backward-to-lower-indentation ()
  "Move backward to the lower indentation."
  (interactive)
  (bufferwizard--point-move
   -1 #'bufferwizard--point-keep-searching-until-indent-lower))

;;;###autoload
(defun bufferwizard-point-forward-to-lower-indentation ()
  "Move forward to the lower indentation."
  (interactive)
  (bufferwizard--point-move
   1 #'bufferwizard--point-keep-searching-until-indent-lower))

;;;###autoload
(defun bufferwizard-point-backward-to-empty-line ()
  "Move backward to empty line."
  (interactive)
  (bufferwizard--point-move
   -1 #'bufferwizard--point-keep-searching-until-empty))

;;;###autoload
(defun bufferwizard-point-forward-to-empty-line ()
  "Move forward to empty line."
  (interactive)
  (bufferwizard--point-move
   1 #'bufferwizard--point-keep-searching-until-empty))

;;; Move region

(defcustom bufferwizard-move-region-skip-invisible t
  "Non-nil means moving the region will skip invisible lines."
  :type 'boolean
  :group 'bufferwizard)

(defun bufferwizard-move-region (n)
  "Move the current region up or down by N lines."
  (when (use-region-p)
    (let ((start (region-beginning))
          (end (region-end)))
      (when (and (bound-and-true-p evil-local-mode)
                 (fboundp 'evil-visual-state-p)
                 (evil-visual-state-p)
                 (fboundp 'evil-exit-visual-state))
        ;; For Evil users: Exit visual state explicitly before performing the
        ;; operation. If we do not do this, Evil will automatically restore the
        ;; original point and mark after the command finishes, overriding any
        ;; cursor movement or region updates made within the function.
        (evil-exit-visual-state))

      (let ((line-text (delete-and-extract-region start end)))
        (if bufferwizard-move-region-skip-invisible
            (forward-visible-line n)
          (forward-line n))
        (let ((start (point)))
          (insert line-text)

          (setq end (point))
          (set-mark end)

          (goto-char start)

          ;; Ensure that the region remains active after the command finishes.
          ;; In Emacs, the variable `deactivate-mark' controls whether the
          ;; region is deactivated automatically at the end of a command. By
          ;; default, it is set to t by many interactive commands, which causes
          ;; the region to be cleared after execution. Setting `deactivate-mark'
          ;; to nil prevents this automatic deactivation. This is necessary even
          ;; when `activate-mark' is called explicitly, because without setting
          ;; `deactivate-mark' to nil, the region may appear briefly and then
          ;; vanish immediately after the function returns, giving the false
          ;; impression that the selection failed.
          (setq deactivate-mark nil)
          (activate-mark))))))

;;;###autoload
(defun bufferwizard-move-region-up (&optional count)
  "Move the current region up by COUNT lines.
If COUNT is omitted, it defaults to 1."
  (interactive "p")
  (bufferwizard-move-region (- (or count 1))))

;;;###autoload
(defun bufferwizard-move-region-down (&optional count)
  "Move the current region down by COUNT lines.
If COUNT is omitted, it defaults to 1."
  (interactive "p")
  (bufferwizard-move-region (or count 1)))

;;; Alternative to `grep'

;;;###autoload
(defun bufferwizard-grep (command-args)
  "Run Grep with user-specified COMMAND-ARGS.
The output from the command goes to the \"*grep*\" buffer.

Unlike the built-in `grep' command, which pre-fills the minibuffer prompt with
the entire base grep command, this command presents a clean, empty prompt. The
user only types the search arguments. The base grep command is prepended
automatically. This reduces visual noise and prevents accidental modification of
required grep flags.

While Grep runs asynchronously, you can use \\[next-error] (M-x next-error), or
\\<grep-mode-map>\\[compile-goto-error] in the *grep* buffer, to go to the lines
where Grep found matches. To kill the Grep job before it finishes, type
\\[kill-compilation].

Non-interactively, COMMAND-ARGS should specify the Grep command-line arguments.

For doing a recursive `grep', see the `rgrep' command. For running Grep in a
specific directory, see `lgrep'.

This command uses a special history list for its COMMAND-ARGS, so you can easily
repeat a grep command.

A prefix argument says to default the COMMAND-ARGS based on the current tag the
cursor is over, substituting it into the last Grep command in the Grep command
history (or into `grep-command' if that history list is empty)."
  (interactive
   (progn
     (require 'grep)
     (when (fboundp 'grep-compute-defaults)
       (grep-compute-defaults))
     (list (read-shell-command
            "Grep: "
            ""
            'grep-history
            (if (fboundp 'grep-default-command)
                (if current-prefix-arg
                    nil
                  (grep-default-command))
              nil)))))

  (require 'grep)
  (require 'files-x) ; null-device
  (let* ((default (if (fboundp 'grep-default-command)
                      (grep-default-command)
                    ""))
         (base-command (if current-prefix-arg
                           default
                         (if (and (boundp 'grep-command-position)
                                  grep-command-position
                                  (boundp 'grep-command)
                                  (stringp grep-command)
                                  (>= (length grep-command)
                                      grep-command-position))
                             (substring grep-command 0 grep-command-position)
                           (if (boundp 'grep-command)
                               grep-command
                             ""))))
         (grep-arguments (concat base-command " " command-args)))
    ;; If called non-interactively, also compute the defaults if we haven't
    ;; already.
    (when (and (boundp 'grep-highlight-matches)
               (eq grep-highlight-matches 'auto-detect)
               (fboundp 'grep-compute-defaults))
      (grep-compute-defaults))
    (when (fboundp 'grep--save-buffers)
      (grep--save-buffers))
    ;; Setting process-setup-function makes exit-message-function work even
    ;; when async processes aren't supported.
    (when (fboundp 'grep-mode)
      (compilation-start
       (let ((null-device (when (fboundp 'null-device)
                            (null-device))))
         (if (and (bound-and-true-p grep-use-null-device)
                  null-device)
             (concat grep-arguments " " null-device)
           grep-arguments))
       #'grep-mode))))

;;; Reload buffer

(defun bufferwizard-reload-current-buffer ()
  "Reload the current buffer from disk, preserving its exact window state.

Unlike the standard `revert-buffer', which only replaces text while retaining
the same buffer object, this function completely kills and re-creates the buffer
via `find-alternate-file'. This acts as a true hard reset that clears corrupted
syntax highlighting, glitched minor modes, or out-of-sync background
tooling (like LSP markers).

If the buffer is modified, it is saved before reloading. The function fully
supports indirect buffers by explicitly destroying and reconstructing them.
Upon completion, it restores the previous point position, horizontal scroll,
pixel-exact vertical scroll, and window start position across all windows
displaying the buffer or its indirect clones, as well as any active narrowing.

If called interactively, it displays a message confirming the reload."
  (interactive)
  (let* ((orig-buffer (current-buffer))
         (base-buffer (or (buffer-base-buffer orig-buffer) orig-buffer))
         (file (buffer-file-name base-buffer)))
    (unless file
      (error "Current buffer is not visiting a file"))

    (unless (file-exists-p file)
      (error "The file doesn't exist: %s" file))

    (let* ((inhibit-redisplay t)
           (indirect-buffers
            (delq nil
                  (mapcar (lambda (buf)
                            (when (eq (buffer-base-buffer buf) base-buffer)
                              buf))
                          (buffer-list))))
           (all-buffers (cons base-buffer indirect-buffers))
           (buffer-states (mapcar
                           (lambda (buf)
                             (with-current-buffer buf
                               (list buf
                                     (buffer-name buf)
                                     (buffer-narrowed-p)
                                     (point-min)
                                     (point-max)
                                     (point)
                                     (mapcar (lambda (win)
                                               (list win
                                                     (window-hscroll win)
                                                     (window-vscroll win t)
                                                     (window-start win)
                                                     (window-point win)))
                                             (get-buffer-window-list buf nil t)))))
                           all-buffers)))

      (when (buffer-modified-p base-buffer)
        (with-current-buffer base-buffer
          (save-buffer)))

      (unless (eq orig-buffer base-buffer)
        (set-window-buffer (selected-window) base-buffer))

      (with-current-buffer base-buffer
        (find-alternate-file file))

      (let ((new-base-buffer (current-buffer)))
        (when (and (buffer-file-name)
                   (string= (file-truename (buffer-file-name))
                            (file-truename file)))
          (dolist (state buffer-states)
            (let* ((old-buf (nth 0 state))
                   (buf-name (nth 1 state))
                   (narrowed (nth 2 state))
                   (min-val (nth 3 state))
                   (max-val (nth 4 state))
                   (point-val (nth 5 state))
                   (win-states (nth 6 state))
                   (target-buf (if (eq old-buf base-buffer)
                                   new-base-buffer
                                 (make-indirect-buffer new-base-buffer buf-name t))))

              (with-current-buffer target-buf
                (when narrowed
                  (narrow-to-region min-val max-val))
                (goto-char point-val))

              (dolist (win-state win-states)
                (let ((win (nth 0 win-state))
                      (hscroll (nth 1 win-state))
                      (vscroll (nth 2 win-state))
                      (start (nth 3 win-state))
                      (wpoint (nth 4 win-state)))
                  (when (window-live-p win)
                    (set-window-buffer win target-buf)
                    (set-window-point win wpoint)
                    (set-window-start win start)
                    (set-window-vscroll win vscroll t)
                    (set-window-hscroll win hscroll))))))

          (when (called-interactively-p 'any)
            (message "Reloaded: %s" (abbreviate-file-name file))))))))

;;; Provide
(provide 'bufferwizard)

;;; bufferwizard.el ends here
